<a href="https://colab.research.google.com/github/OMatheusWander/CienciadeDadosUFSC/blob/Algebra_Linear_para_Ciencia_de_Dados/ALGEBRA_LINEAR_PARA_DADOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AULA 1

In [ ]:
for i,j in range (5):
  print(ij )
  i+=1

# Matriz com congruência em python

In [ ]:
#Baixar bibliotecas
import numpy as np


In [ ]:
from IPython.utils.path import ensure_dir_exists
#Transposição de matrizes

A = np.array([[1,2],[3,4]])
B = np.array([[1,2,3],[4,5,6]])

Af = [[1,2],[3,4]]
Bf = [[1,2,3],[4,5,6]]
print(Bf)
#Código para transposição de matrizes



# print(A)
# print()

def matriz_transposta(A):
  for i in range(Af[][0]):
    for j in range(A.shape[1]):
      print(A[j,i],sep = " ",end = " ")
    print()

matriz_transposta(Af)

SAB = np.array()

# def matriz_soma(A,B):
#   for i in range(A.shape):
#     for j in range(B.shape):
      #SAB[i,j] = Af[] + Bf[]






[[1, 2, 3], [4, 5, 6]]


AttributeError: 'list' object has no attribute 'shape'

In [ ]:
# Com lista pura

Af = [[1,2],[3,4]]
Bf = [[1,2,3],[4,5,6]]

#Código para transposição de matrizes

def matriz_transposta(Af):
  for i in range(len(Af)):
    At=[]
    for j in range(len(Af)):
      #print(Af[j][i])
      At.append(Af[j][i])
    print(At)


matriz_transposta(Af)

# SAB = np.array()

# def matriz_soma(A,B):
#   for i in range(A.shape):
#     for j in range(B.shape):
      #SAB[i,j] = Af[] + Bf[]






[1, 3]
[2, 4]


In [ ]:
#Soma de matrizes sem numpy

Af = [[1,2],[3,4]]
Bf = [[1,2],[4,5]]

#Código para soma de matrizes

def matriz_soma(Af,Bf):
  for i in range(len(Af)):
    SAB=[]
    for j in range(len(Af)):
      SAB.append(Af[i][j] + Bf[i][j])

    print(SAB)

matriz_soma(Af,Bf)



[2, 4]
[7, 9]


In [ ]:
#Multiplicação de matrizes

Af = [[1,2],[3,4]]
Bf = [[1,2],[4,5]]

#Código para multiplicação de matrizes

def matriz_multiplicacao(Af,Bf,k):
  for i in range(len(Af)):
    Ak=[]
    for j in range(len(Af)):
      Ak.append(Af[i][j] * k)

    print(Ak)

matriz_multiplicacao(Af,Bf,5)



[5, 10]
[15, 20]


In [ ]:
#Multiplicação de matrizes

#Código para multiplicação de matrizes

def matriz_multiplicacao(Af,Bf,k):
  for i in range(len(Af)):
    Ak=[]
    for j in range(len(Af)):
      Ak.append(Af[i][j] * B)

    print(Ak)

matriz_multiplicacao(Af,Bf,5)


Sistemas Lineares

In [ ]:
#AX = B

A = [
    [3,-1,2,3],
    [0,2,3,-1],
    [0,0,5,7],
    [0,0,0,3]
]

X1,X2,X3,X4 = []


X = [
    X1,X2,X3,X4
]

B = [
    [12,11,2,5]
]


#Algoritmo de resolução de sistemas lineares


#fazer



In [ ]:
#Método de Escalonamento






In [ ]:
#3 Operações Elementares

#Trocar, Multiplicar e trocar multiplicando




def matriz_troca_linha(matriz,linha_1, linha_2):
  for i in matriz:
    for j in matriz:
      if i == linha__1:


AULA 3

In [ ]:
def escalonamento_logica_bruta(A, b):
    # 1. Criar matriz aumentada manualmente
    n = len(A)
    cols = len(A[0])
    matriz = []
    for i in range(n):
        linha = []
        for j in range(cols):
            linha.append(float(A[i][j]))
        linha.append(float(b[i]))
        matriz.append(linha)

    print("Matriz Aumentada Inicial:")
    for l in matriz: print(l)
    print("-" * 30)

    # Gauss-Jordan
    for i in range(n):
        # Encontrar pivô (Lógica bruta de busca)
        max_val = abs(matriz[i][i])
        max_row = i
        for k in range(i + 1, n):
            if abs(matriz[k][i]) > max_val:
                max_val = abs(matriz[k][i])
                max_row = k

        # Troca de linhas manual
        if max_row != i:
            matriz[i], matriz[max_row] = matriz[max_row], matriz[i]
            print(f"Passo: Troca L{i} <-> L{max_row}")
            for l in matriz: print(l)

        # Normalização do pivô
        pivo = matriz[i][i]
        if pivo != 0:
            for j in range(i, cols + 1):
                matriz[i][j] /= pivo
            print(f"Passo: L{i} = L{i} / {pivo:.2f}")
            for l in matriz: print(l)

        # Eliminação (Zerar coluna)
        for k in range(n):
            if k != i:
                fator = matriz[k][i]
                if fator != 0:
                    for j in range(i, cols + 1):
                        matriz[k][j] = matriz[k][j] - (fator * matriz[i][j])
                    print(f"Passo: L{k} = L{k} - ({fator:.2f}) * L{i}")
                    for l in matriz: print(l)
        print("-" * 30)

    return matriz

# Dados de teste
A_teste = [[3, -1, 2], [1, 2, 3], [2, -2, 2]]
B_teste = [12, 11, 2]

resultado = escalonamento_logica_bruta(A_teste, B_teste)

Matriz Aumentada Inicial:
[3.0, -1.0, 2.0, 12.0]
[1.0, 2.0, 3.0, 11.0]
[2.0, -2.0, 2.0, 2.0]
------------------------------
Passo: L0 = L0 / 3.00
[1.0, -0.3333333333333333, 0.6666666666666666, 4.0]
[1.0, 2.0, 3.0, 11.0]
[2.0, -2.0, 2.0, 2.0]
Passo: L1 = L1 - (1.00) * L0
[1.0, -0.3333333333333333, 0.6666666666666666, 4.0]
[0.0, 2.3333333333333335, 2.3333333333333335, 7.0]
[2.0, -2.0, 2.0, 2.0]
Passo: L2 = L2 - (2.00) * L0
[1.0, -0.3333333333333333, 0.6666666666666666, 4.0]
[0.0, 2.3333333333333335, 2.3333333333333335, 7.0]
[0.0, -1.3333333333333335, 0.6666666666666667, -6.0]
------------------------------
Passo: L1 = L1 / 2.33
[1.0, -0.3333333333333333, 0.6666666666666666, 4.0]
[0.0, 1.0, 1.0, 3.0]
[0.0, -1.3333333333333335, 0.6666666666666667, -6.0]
Passo: L0 = L0 - (-0.33) * L1
[1.0, 0.0, 1.0, 5.0]
[0.0, 1.0, 1.0, 3.0]
[0.0, -1.3333333333333335, 0.6666666666666667, -6.0]
Passo: L2 = L2 - (-1.33) * L1
[1.0, 0.0, 1.0, 5.0]
[0.0, 1.0, 1.0, 3.0]
[0.0, 0.0, 2.0, -2.0]
---------------------

Resolver o 1.18 no calculo
2.12
exemplo 2.5



1)ESCALONAMENTO COMPLETO (SISTEMAS) (Não esquecer o B)

2)INVERSA PELA IDENTIDADE (ESCALONA... (A:I)~~(I:A^-1)

3)Salvar as E1,2 -> Calcula a inversa pelo produto da E1,2
INVERSA PELA AMPLIADA COM O PRODUTO DAS ELEMENTARES

In [ ]:
#Exercício 1

#Escalonamento completo de sistemas

import numpy as np
print("Exercício 1")
print()

print('Matriz A')

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)
print()

print('Matriz B')

B = np.array([[4],[2],[7]])
print(B)

#Acrescentar matriz


print()
print("Matriz A|B")
AB = np.hstack((A,B))
print(AB)
AB_original = AB
#Primeira coluna
print()

dic_mat = {}

for i, j in enumerate(AB):
    pivo = j[i]                      # elemento da diagonal
    x = 1 / pivo if pivo != 0 else 1
    dic_mat[i] = [round(float(x * elem),2) for elem in j]

print(dic_mat)

print()


# Troca a linha 0 com a linha 1
A[[0, 1]] = A[[1, 0]]

print(A)

Exercício 1

Matriz A
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B
[[4]
 [2]
 [7]]

Matriz A|B
[[1 2 3 4]
 [4 5 6 2]
 [7 8 9 7]]

{0: [1.0, 2.0, 3.0, 4.0], 1: [0.8, 1.0, 1.2, 0.4], 2: [0.78, 0.89, 1.0, 0.78]}

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [ ]:
#Exercício 2
import numpy as np
print("Exercício 2")
print()

I = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(I)

Exercício 2

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
Sistema triangular inferior

Ao invés do escalonamento ser o maior número



Soma de matrizes

## Funções Matriciais em Numpy



In [ ]:
import numpy as np

In [ ]:
print('Matriz A')

A = np.array([[1,2,8],[4,6,2],[7,8,4]])

print(A)
print()

print('Matriz B')

B = np.array([[4,2,2],[2,9,1],[7,9,6]])
print(B)


Matriz A
[[1 2 8]
 [4 6 2]
 [7 8 4]]

Matriz B
[[4 2 2]
 [2 9 1]
 [7 9 6]]


In [ ]:
#Soma de Matrizes

In [ ]:
#A + B

soma_ab = A + B
print(soma_ab)

[[ 5  4  8]
 [ 6 14 14]
 [14 17  9]]


In [ ]:
#Multiplicação de Matriz por K

In [ ]:
k = 9
# print(A)
print()
mult_ak = A * k
print(mult_ak)


[[ 9 18 72]
 [36 54 18]
 [63 72 36]]


In [ ]:
#Multiplicação de Matrizes

In [ ]:
mult_ab = A @ B
# print(A)
# print()
# print(B)
# print()
print(mult_ab)

[[ 64  92  52]
 [ 42  80  26]
 [ 72 122  46]]


In [ ]:
#Matriz Transposta

In [ ]:
At = np.transpose(A)
# print(A)
# print()
print(At)

[[1 4 7]
 [2 6 8]
 [8 2 4]]


##Gaus-Jordan
* (a) Trocar a posição de duas linhas da matriz;
* (b) Multiplicar uma linha da matriz por um escalar diferente de zero;
* (c) Somar a uma linha da matriz um múltiplo escalar de outra linha.

In [ ]:
G = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(G)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#Troca de posição de duas linhas em uma matriz
print(A)
print()
A[[0,2]] = A[[2,0]] #Troca da linha 0 e pela linha 2
print()
print(A)

[[1 2 8]
 [4 6 2]
 [7 8 4]]


[[7 8 4]
 [4 6 2]
 [1 2 8]]


In [ ]:
#Multiplicar um linha da matriz por um escalar diferente de zero
A = np.array([[1,2,8],[4,6,2],[7,8,4]])
print(A)

print()
A[0] = A[[0]] * 3
print(A)

[[1 2 8]
 [4 6 2]
 [7 8 4]]

[[ 3  6 24]
 [ 4  6  2]
 [ 7  8  4]]


In [ ]:
#Somar a uma linha da matriz um múltiplo escalar de outra linha.

In [ ]:
A = np.array([[1,2,8],[4,6,2],[7,8,4]])
print(A)
print()

A[[2]] = A [[2]] + (A[0] * -7)
print(A)

[[1 2 8]
 [4 6 2]
 [7 8 4]]

[[  1   2   8]
 [  4   6   2]
 [  0  -6 -52]]


In [ ]:
#Determinante

In [ ]:
det_A = np.linalg.det(A)
print(A)

print(det_A)

[[  1   2   8]
 [  4   6   2]
 [  0  -6 -52]]
-76.0


In [ ]:
#Matriz Cofator

In [ ]:
print(A)
print()

def cofator(Matriz,linha,coluna):
  print(A[0][1])
  print()


  for i in A:
    if i == linha -1:
      for j in i:
        if j == coluna:
          np.delete(A,linha,coluna)


[[  1   2   8]
 [  4   6   2]
 [  0  -6 -52]]

2

1
2
8
4
6
2
0
-6
-52


In [ ]:
print(A)
print()

a = np.delete(A,1,1)
print(a)

[[  1   2   8]
 [  4   6   2]
 [  0  -6 -52]]

[[  1   8]
 [  4   2]
 [  0 -52]]


In [ ]:
#Laplace

In [ ]:
#Calcular a inversa pela ajunta (pg 124 na página do livro)