<a href="https://colab.research.google.com/github/OMatheusWander/CienciadeDadosUFSC/blob/Algebra_Linear_para_Ciencia_de_Dados/Prova_1_%C3%81lgebra_Linear_para_Ci%C3%AAncia_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PROVA 1

##Bibliotecas e Matrizes bases

In [1]:
import numpy as np
import random

TOLERANCIA = 1e-10  # valores menores que isso são tratados como zero

A = np.array([[2, 0],[6, 7]])
B = np.array([[0, 4],[2, -8]])
C = np.array([[-6, 9, -7],[7, -3, -2]])
D = np.array([[-6, 4, 0],[1, 1, 4],[-6, 0, 6]])
E = np.array([[6, 9, -9],[-1, 0, 4], [-6, 0, 6]])

##Funções Elementares de Matrizes

In [2]:
def dimensoes(matriz):
    linhas = matriz.shape[0]
    colunas = matriz.shape[1]
    return linhas, colunas

def multiplicacao_matrizes(A, B):
    linhas_a, colunas_a = dimensoes(A)
    linhas_b, colunas_b = dimensoes(B)

    if colunas_a != linhas_b:
        raise ValueError("Nº de colunas de A deve ser igual ao nº de linhas de B.")

    C = np.zeros((linhas_a, colunas_b))
    for i in range(linhas_a):
        for j in range(colunas_b):
            soma = 0.0
            for k in range(colunas_a):
                soma = soma + A[i, k] * B[k, j]
            C[i, j] = soma
    return C

def soma_matrizes(A, B):
    linhas_a, colunas_a = dimensoes(A)
    linhas_b, colunas_b = dimensoes(B)

    if linhas_a != linhas_b or colunas_a != colunas_b:
        raise ValueError("As matrizes precisam ter as mesmas dimensões para a soma.")

    C = np.zeros((linhas_a, colunas_a))
    for i in range(linhas_a):
        for j in range(colunas_a):
            C[i, j] = A[i, j] + B[i, j]
    return C

def subtracao_matrizes(A, B):
    linhas_a, colunas_a = dimensoes(A)
    linhas_b, colunas_b = dimensoes(B)

    if linhas_a != linhas_b or colunas_a != colunas_b:
        raise ValueError("As matrizes precisam ter as mesmas dimensões para a subtração.")

    C = np.zeros((linhas_a, colunas_a))
    for i in range(linhas_a):
        for j in range(colunas_a):
            C[i, j] = A[i, j] - B[i, j]
    return C

def multiplicacao_escalar(k, A):
    linhas, colunas = dimensoes(A)
    C = np.zeros((linhas, colunas))
    for i in range(linhas):
        for j in range(colunas):
            C[i, j] = k * A[i, j]
    return C

def trocar_linhas(matriz, linha_a, linha_b):
    colunas = matriz.shape[1]
    for j in range(colunas):
        temporario = matriz[linha_a, j]
        matriz[linha_a, j] = matriz[linha_b, j]
        matriz[linha_b, j] = temporario

##Questão 1

In [3]:
# a)

#AB é diferente de BA?


In [77]:
AB = multiplicacao_matrizes(A,B)
print(AB)

[[  0.   8.]
 [ 14. -32.]]


In [78]:
BA = multiplicacao_matrizes(B,A)
print(BA)

[[ 24.  28.]
 [-44. -56.]]


In [6]:
#b)AB-BA

In [7]:
AB = multiplicacao_matrizes(A,B)
BA = multiplicacao_matrizes(B,A)

subtracao_matrizes(AB,BA)

array([[-24., -20.],
       [ 58.,  24.]])

In [8]:
#c)2C - D (É possível? Porque?)

In [9]:
dois_C = multiplicacao_escalar(2, C)
print("Dimensões de 2C:", dimensoes(dois_C))
print("Dimensões de D:", dimensoes(D))

if dimensoes(dois_C) == dimensoes(D):
    questao_c = subtracao_matrizes(dois_C, D)
    print("Resultado de 2C - D:")
    print(questao_c)
else:
    print("A subtração 2C - D não é possível porque as matrizes não têm as mesmas dimensões.")

ValueError: As matrizes precisam ter as mesmas dimensões para a subtração.

In [83]:
#d)(2D^t - 3E^t)^t
#(2D - 3E) por propriedade
dois_d = multiplicacao_escalar(2,D)
print(dois_d)
print()

tres_e = multiplicacao_escalar(3,E)
print(tres_e)
print()

sub_d_e = subtracao_matrizes(dois_d,tres_e)
print()
print("Subtração de D - E:")
print()
print(sub_d_e)

[[-12.   8.   0.]
 [  2.   2.   8.]
 [-12.   0.  12.]]

[[ 18.  27. -27.]
 [ -3.   0.  12.]
 [-18.   0.  18.]]


Subtração de D - E:

[[-30. -19.  27.]
 [  5.   2.  -4.]
 [  6.   0.  -6.]]


In [28]:
#e)D^2 - DE
d_ao_cubo = multiplicacao_matrizes(D,D)
print(d_ao_cubo)
print()

de = multiplicacao_matrizes(D,E)
print(de)
print()

sub_d_e = subtracao_matrizes(d_ao_cubo,de)
sub_d_e

[[ 40. -20.  16.]
 [-29.   5.  28.]
 [  0. -24.  36.]]

[[-40. -54.  70.]
 [-19.   9.  19.]
 [-72. -54.  90.]]



array([[ 80.,  34., -54.],
       [-10.,  -4.,   9.],
       [ 72.,  30., -54.]])

##Questão 2

In [124]:
A_Q2 = np.array([[0,1,0], [0,0,1], [0,0,0]])
A_quadrado = multiplicacao_matrizes(A_Q2,A_Q2) #A^2
print(A_quadrado)
print()

A_cubo = multiplicacao_matrizes(A_quadrado,A_Q2)
print(A_cubo)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##Questão 3

In [125]:
matriz_randomica_ordem_10 = np.random.randint(-10, 10, size=(10, 10))
# fonte:https://numpy.org/devdocs/reference/random/generated/numpy.random.randint.html

print(matriz_randomica_ordem_10)

def soma_elementos_nao_diagonais(matriz):
    linhas, colunas = dimensoes(matriz)
    soma = 0
    for i in range(linhas):
        for j in range(colunas):
            if i != j:
                soma += matriz[i, j]
    return soma

# print()
# def soma_de_linha(matriz,linha):
#     linhas, colunas = dimensoes(matriz)
#     soma = 0
#     for i in range(colunas):
#         soma += matriz[linha, i]
#     return soma

#TESTE
# print(soma_elementos_nao_diagonais(matriz_randomica_ordem_10))
# soma_de_linha(matriz_randomica_ordem_10,0)

[[  5   0   0  -6   3   7  -8   8   3   9]
 [  5   2  -9   5  -7  -2  -2  -8   1  -6]
 [  8  -5   2  -2  -4   8   1   2  -5  -3]
 [  1   7   8 -10  -5  -7  -5   3   3   6]
 [ -1 -10   3   0   1  -3   1  -1   9  -3]
 [ -8   3  -3  -5   9  -7   5  -9  -7   8]
 [ -1   7   8   7  -1  -3   1 -10   2  -9]
 [ -5   8  -4  -8  -6   2 -10  -7   9  -2]
 [  9   9   4   0   5  -6   1  -5  -9 -10]
 [ -7   6   2   4   4  -9   5  -7 -10  -8]]


##Questão 4

In [105]:
#Definindo as matrizes de teste

A1 = np.array([[3, 0, 0], [1, 2, 0], [2, -4, 1]])
B1 = np.array([[9],[5],[7]])
S1 = np.array([[3],[1],[5]])

A2 = np.array([[2,0,0],[1,2,0],[2,4,1]])
B2 = np.array([[1],[-2],[-12]])
S2 = np.array([[0.5],[-1.25],[-8]])

A3 = np.array([[-4,0,0,0],[7,-1,0,0],[4,6,-2,0],[1,-3,6,5]])
B3 = np.array([[4,-10,16,-1]])

In [104]:
def posto(matriz):#número de linhas não nulas após escalonamento.
    R, colunas_pivo = forma_escalonada_reduzida(matriz)
    linhas, colunas = dimensoes(R)
    contador = 0
    for i in range(linhas):
        linha_nula = True
        for j in range(colunas):
            if abs(R[i, j]) > TOLERANCIA:
                linha_nula = False
                break
        if not linha_nula:
            contador = contador + 1
    return contador
def forma_escalonada_reduzida(A, colunas_pivo_limite=None):
    R = A.astype(float).copy()
    linhas, colunas = dimensoes(R)

    if colunas_pivo_limite is None:
        colunas_pivo_limite = colunas

    colunas_pivo = []
    linha_pivo = 0

    for coluna in range(colunas_pivo_limite):
        if linha_pivo >= linhas:
            break

        # 1) Pivoteamento parcial
        indice_maior = linha_pivo
        maior_valor = abs(R[linha_pivo, coluna])
        for i in range(linha_pivo + 1, linhas):
            if abs(R[i, coluna]) > maior_valor:
                maior_valor = abs(R[i, coluna])
                indice_maior = i

        if maior_valor < TOLERANCIA:
            continue

        if indice_maior != linha_pivo:
            trocar_linhas(R, linha_pivo, indice_maior)
            #passo a passo
            print(f"L{linha_pivo + 1} <-> L{indice_maior + 1}")

        # 2) Normaliza a linha do pivô: Lpivo = Lpivo / pivo
        pivo = R[linha_pivo, coluna]
        for j in range(colunas):
            R[linha_pivo, j] = R[linha_pivo, j] / pivo
        #passo a passo
        print(f"L{linha_pivo + 1} = L{linha_pivo + 1} / ({pivo:.4f})")

        # 3) Zera a coluna do pivô em TODAS as outras linhas (acima e abaixo)
        for i in range(linhas):
            if i == linha_pivo:
                continue
            fator = R[i, coluna]
            if abs(fator) > TOLERANCIA:
                for j in range(colunas):
                    R[i, j] = R[i, j] - fator * R[linha_pivo, j]
                #passo a passo
                print(f"L{i + 1} = L{i + 1} - ({fator:.4f}) * L{linha_pivo + 1}")

        colunas_pivo.append(coluna)
        linha_pivo = linha_pivo + 1

    return (R), colunas_pivo


def resolver_sistema(A, b, mostrar_passos=False):
    linhas, n_incognitas = dimensoes(A)
    b_coluna = b.astype(float).reshape(linhas, 1)

    # Monta a matriz aumentada [A | b]
    aumentada = np.zeros((linhas, n_incognitas + 1))
    for i in range(linhas):
        for j in range(n_incognitas):
            aumentada[i, j] = A[i, j]
        aumentada[i, n_incognitas] = b_coluna[i, 0]

    #matriz
        print(aumentada, "Matriz aumentada [A | b]:")

    R, colunas_pivo = forma_escalonada_reduzida(aumentada, colunas_pivo_limite=n_incognitas)

    posto_a = posto(A)
    posto_aumentada = posto(aumentada)

    resultado = {
        "matriz_reduzida": R,
        "posto_A": posto_a,
        "posto_aumentada": posto_aumentada,
        "solucao": None,
        "variaveis_livres": [],
    }

    if posto_a != posto_aumentada:
        resultado["classificacao"] = "SI - Sistema Impossível"
        return resultado

    if posto_a == n_incognitas:
        resultado["classificacao"] = "SPD - Sistema Possível e Determinado"
        solucao = np.zeros(n_incognitas)
        for indice_linha in range(len(colunas_pivo)):
            coluna = colunas_pivo[indice_linha]
            solucao[coluna] = R[indice_linha, n_incognitas]
        resultado["solucao"] = solucao
        return resultado

    # SPI: descreve cada variável pivô em função das livres
    resultado["classificacao"] = "SPI - Sistema Possível e Indeterminado"
    variaveis_livres = []
    for j in range(n_incognitas):
        if j not in colunas_pivo:
            variaveis_livres.append(j)
    resultado["variaveis_livres"] = variaveis_livres

    expressoes = []
    for indice_linha in range(len(colunas_pivo)):
        coluna = colunas_pivo[indice_linha]
        texto = f"x{coluna + 1} = {R[indice_linha, n_incognitas]:.4f}"
        for livre in variaveis_livres:
            coeficiente = -R[indice_linha, livre]
            if abs(coeficiente) > TOLERANCIA:
                if coeficiente > 0:
                    texto = texto + f" + {coeficiente:.4f}*x{livre + 1}"
                else:
                    texto = texto + f" - {abs(coeficiente):.4f}*x{livre + 1}"
        expressoes.append(texto)
    for livre in variaveis_livres:
        expressoes.append(f"x{livre + 1} livre")
    resultado["solucao"] = expressoes
    return resultado

print("Exemplo 1:")
print(resolver_sistema(A1,B1))
print()

print("Exemplo 2:")
print(resolver_sistema(A2,B2))
print()

print("Exemplo 3:")
print(resolver_sistema(A3,B3))
print()

Exemplo 1:
[[3. 0. 0. 9.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] Matriz aumentada [A | b]:
[[3. 0. 0. 9.]
 [1. 2. 0. 5.]
 [0. 0. 0. 0.]] Matriz aumentada [A | b]:
[[ 3.  0.  0.  9.]
 [ 1.  2.  0.  5.]
 [ 2. -4.  1.  7.]] Matriz aumentada [A | b]:
L1 = L1 / (3.0000)
L2 = L2 - (1.0000) * L1
L3 = L3 - (2.0000) * L1
L2 <-> L3
L2 = L2 / (-4.0000)
L3 = L3 - (2.0000) * L2
L3 = L3 / (0.5000)
L2 = L2 - (-0.2500) * L3
L1 = L1 / (3.0000)
L2 = L2 - (1.0000) * L1
L3 = L3 - (2.0000) * L1
L2 <-> L3
L2 = L2 / (-4.0000)
L3 = L3 - (2.0000) * L2
L3 = L3 / (0.5000)
L2 = L2 - (-0.2500) * L3
L1 = L1 / (3.0000)
L2 = L2 - (1.0000) * L1
L3 = L3 - (2.0000) * L1
L2 <-> L3
L2 = L2 / (-4.0000)
L3 = L3 - (2.0000) * L2
L3 = L3 / (0.5000)
L2 = L2 - (-0.2500) * L3
{'matriz_reduzida': array([[1., 0., 0., 3.],
       [0., 1., 0., 1.],
       [0., 0., 1., 5.]]), 'posto_A': 3, 'posto_aumentada': 3, 'solucao': array([3., 1., 5.]), 'variaveis_livres': [], 'classificacao': 'SPD - Sistema Possível e Determinado'}

Exemplo 2:
[[2. 0. 

##Questão 5

In [106]:
#Gaus parcial

def triangular_superior(matriz):
    print("Matriz original:")
    print(matriz)
    print()
    U = matriz.astype(float).copy()
    linhas, colunas = dimensoes(U)
    numero_trocas = 0

    linha_pivo = 0
    for coluna in range(colunas):
        if linha_pivo >= linhas:
            break

        #procura o maior valor absoluto na coluna
        indice_maior = linha_pivo
        maior_valor = abs(U[linha_pivo, coluna])
        for i in range(linha_pivo + 1, linhas):
            if abs(U[i, coluna]) > maior_valor:
                maior_valor = abs(U[i, coluna])
                indice_maior = i

        #passa para a próxima coluna
        if maior_valor < TOLERANCIA:
            continue

        #troca de linhas, se necessário
        if indice_maior != linha_pivo:
            trocar_linhas(U, linha_pivo, indice_maior)
            numero_trocas = numero_trocas + 1
            #passo a passo
            print(f"L{linha_pivo + 1} <-> L{indice_maior + 1}")

        #zera os elementos abaixo do pivô: Li = Li - (fator * Lpivo)
        for i in range(linha_pivo + 1, linhas):
            fator = U[i, coluna] / U[linha_pivo, coluna]
            if abs(fator) > TOLERANCIA:
                for j in range(colunas):
                    U[i, j] = U[i, j] - fator * U[linha_pivo, j]
                #passo a passo
                    print(f"L{i + 1} = L{i + 1} - ({fator:.4f}) * L{linha_pivo + 1}")

        #passo a passo
            print((U))

        linha_pivo = linha_pivo + 1

    return U, numero_trocas

triangular_superior(D)

Matriz original:
[[-6  4  0]
 [ 1  1  4]
 [-6  0  6]]

L2 = L2 - (-0.1667) * L1
L2 = L2 - (-0.1667) * L1
L2 = L2 - (-0.1667) * L1
[[-6.          4.          0.        ]
 [ 0.          1.66666667  4.        ]
 [-6.          0.          6.        ]]
L3 = L3 - (1.0000) * L1
L3 = L3 - (1.0000) * L1
L3 = L3 - (1.0000) * L1
[[-6.          4.          0.        ]
 [ 0.          1.66666667  4.        ]
 [ 0.         -4.          6.        ]]
L2 <-> L3
L3 = L3 - (-0.4167) * L2
L3 = L3 - (-0.4167) * L2
L3 = L3 - (-0.4167) * L2
[[-6.   4.   0. ]
 [ 0.  -4.   6. ]
 [ 0.   0.   6.5]]


(array([[-6. ,  4. ,  0. ],
        [ 0. , -4. ,  6. ],
        [ 0. ,  0. ,  6.5]]),
 1)

##Questão 6

In [128]:
def submatriz_menor(matriz, linha_removida, coluna_removida):
    n = matriz.shape[0]
    menor = np.zeros((n - 1, n - 1)) #array inteiro de zeros
    nova_i = 0
    for i in range(n):
        if i == linha_removida:
            continue
        nova_j = 0
        for j in range(n):
            if j == coluna_removida:
                continue
            menor[nova_i, nova_j] = matriz[i, j]
            nova_j = nova_j + 1
        nova_i = nova_i + 1
    return menor

def determinante_matriz_qualquer_ordem(matriz):
    linhas, colunas = dimensoes(matriz)
    if range(linhas) != range(colunas):
        raise ValueError("O determinante só existe para matrizes quadradas.")
    n = matriz.shape[0]
    if n == 1:
        return matriz[0, 0]
    if n == 2:
        return matriz[0, 0] * matriz[1, 1] - matriz[0, 1] * matriz[1, 0]
    soma = 0.0
    for j in range(n):
        if j % 2 == 0: sinal = 1
        else: sinal = -1
        menor = submatriz_menor(matriz, 0, j)
        soma = soma + sinal * matriz[0, j] * determinante_matriz_qualquer_ordem(menor)
    return soma

print(determinante_matriz_qualquer_ordem(A3))

int(np.linalg.det(A3))

-40.0


-39

#Testes

In [42]:
# print(A)
# linhas = A.shape[0]
# colunas = A.shape[1]
# print(linhas)
# print(colunas)

[[2 0]
 [6 7]]
2
2


In [47]:
# print(A)
# def teste(matriz):
#     linhas, colunas = dimensoes(matriz)
#     print(linhas)
#     print(colunas)
#     soma = 0
#     for i in range(linhas):
#             for j in range(colunas):
#                 if i != j:
#                     soma += matriz[i, j]
#                     print(soma)


# teste(A)

[[2 0]
 [6 7]]
2
2
0
6


In [48]:
# def soma_teste(matriz):
#     linhas, colunas = dimensoes(matriz)
#     soma = 0
#     for i in range(linhas):
#         for j in range(colunas):
#           soma += matriz[i, j]
#     return soma
# soma_teste(A)

np.int64(15)